### ISSUE TITLE
Need logging system

### ISSUE THREAD

**Issue by mr-glt** [mr-glt/FRC-2017-Command#6]
We need a log of what is happening on board the robot for troubleshooting purposes. This is especially valuable for debugging autonomous runs. It would be helpful to have it log to the driver laptop for quicker debugging.

**Comment by jrmihalick** [comment]
Thanks for putting this in Charlie.  The big concern would be that we don't want to capture/log too much or too often because this could result in too much data being logged to be useful and it could hurt performance some. You should look at capturing key output for each command into an Object that can then be dumped out upon termination (successful or unsuccessful) of the command.  You can use slf4j (preferred) or apache log4j to dump the data to a logfile on the RIO. Using one of these APIs will give us flexibility to log to STDOUT or a file. These tools also will make it easy to turn logging on and off.  This will be handy in case we have a problem due to logging or if we find that it isn't useful.
